trigger:
  branches:
    include:
      - develop
      - feat/harness-refactor

pool:
  vmImage: ubuntu-latest

variables:
  SNOWFLAKE_DB_ACCOUNT: "$(snowflake_db_account)"
  SNOWFLAKE_DB_USER: "$(snowflake_db_user)"
  SNOWFLAKE_DB_PW: "$(snowflake_db_pw)"
  SNOWFLAKE_DB_ROLE: "$(snowflake_db_role)"
  SNOWFLAKE_DB_DATABASE: "$(snowflake_db_database)"
  SNOWFLAKE_DB_WH: "$(snowflake_db_wh)"
  SNOWFLAKE_DB_SCHEMA: "$(snowflake_db_schema)"

stages:
  - stage: 'Build_environment'
    jobs:
      - job: 'InstallDependencies'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
          - script: pip install pipenv
            displayName: 'Install pipenv'
          - script: pipenv install --dev
            displayName: 'Install Pipenv dependencies'
          - script: pipenv run inv run-harness-tests
            displayName: 'Harness Tests'
          - script: pipenv run inv run-macro-tests -p snowflake
            displayName: 'Macro Tests - Snowflake'

      - job: 'UnitTests'

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
            displayName: 'Harness Tests'
          - script: inv run-macro-tests -p snowflake
            displayName: 'Macro Tests - Snowflake'